### ISSUE TITLE
Latest Infistar Update

### ISSUE THREAD

**Issue by Gr8z** [ebaydayz/ESSV2#2]
With the latest infistar update, the Air Spawn is bugged for non admins.

**Comment by ebaydayz** [comment]
What version number specifically? The latest I have tested with is 417.

**Comment by Gr8z** [comment]
The most recent - 1419

**Comment by ebaydayz** [comment]
Infi added a check in his antiTP that reverts the teleport if the player is in a vehicle with an AI driver. I just removed the AI pilot for now. He may end up taking that out, we will see. Here is the temp fix:
https://github.com/ebaydayz/ESSV2/commit/45a2ef740e7ee4b940c3d62324a0cfcd32c32b4d

The other problem is his new added keybinds check. He needs to add exceptions to it for BIS_fnc_halo since that function adds several keybinds for steering the parachute. I would disable that check for now or else players will get kicked any time they halo jump from any air vehicle. In AHconfig.sqf:
<pre><code>/*  Check Keybinds ?      */ _CKD =  false;	/* true or false */	/* checks for additional keybinds.. */</code></prec>

**Comment by Gr8z** [comment]
Thanks a bunch @ebaydayz for the Fix

**Comment by ebaydayz** [comment]
Rather than remove the pilot and have the plane crash it is easier to just remove these lines from infistar AH.sqf:
<pre><code>_aidriver = true;
player setVectorUp [0,0,1];
player setVelocity [0,0,0];
player setPosATL _lastPos;</code></pre>

I reverted the pull request and added that to the install directions.
